const unified = require('unified')
    , stream = require('unified-stream')
    , md = require('remark-parse')
    , abbr = require('remark-abbr')
    , toc = require('remark-toc')
    , behead = require('remark-behead')
    , md2html = require('remark-rehype')
    // , slug = require('rehype-slug')
    , processor = unified()
                  .use(md, { gfm: true })
                  .use(abbr, {})
                  .use(toc, {})
                  .use( behead
                      , { depth: 1 }
                      )
                  .use(md2html, {})
// .use(slug)
process.stdin
.pipe(stream(processor))
.pipe(process.stdout)
